"""content schema

Revision ID: 0002_content_schema
Revises: 0001_admin_foundation
Create Date: 2026-09-23 20:25:55.577337
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0002_content_schema'
down_revision = '0001_admin_foundation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_entries',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('start_label', sa.String(length=64), nullable=True),
    sa.Column('end_label', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entry_type in ('education','experience','milestone')", name=op.f('ck_career_entries_career_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_entries'))
    )
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index('ix_contact_messages_created_at', 'contact_messages', ['created_at'], unique=False)
    op.create_index('ix_contact_messages_is_read', 'contact_messages', ['is_read'], unique=False)
    op.create_table('education_entries',
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('start_label', sa.String(length=64), nullable=True),
    sa.Column('end_label', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_entries'))
    )
    op.create_table('expertise_items',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expertise_items'))
    )
    op.create_table('music_settings',
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoplay', sa.Boolean(), nullable=False),
    sa.Column('default_volume', sa.Integer(), nullable=False),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_volume between 0 and 100', name=op.f('ck_music_settings_volume_range')),
    sa.CheckConstraint('id = 1', name=op.f('ck_music_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music_settings'))
    )
    op.create_table('skill_categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_skill_categories_slug'))
    )
    op.create_table('social_links',
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('href', sa.String(length=512), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    op.create_table('media_assets',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('folder', sa.String(length=128), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('image','video','audio','document')", name=op.f('ck_media_assets_media_kind_valid')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['admin_users.id'], name=op.f('fk_media_assets_uploaded_by_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index('ix_media_assets_checksum', 'media_assets', ['checksum'], unique=False)
    op.create_index('ix_media_assets_folder', 'media_assets', ['folder'], unique=False)
    op.create_index('ix_media_assets_kind', 'media_assets', ['kind'], unique=False)
    op.create_table('publish_snapshots',
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('pending','building','published','failed')", name=op.f('ck_publish_snapshots_snapshot_status_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], name=op.f('fk_publish_snapshots_created_by_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_snapshots'))
    )
    op.create_index('ix_publish_snapshots_created_at', 'publish_snapshots', ['created_at'], unique=False)
    op.create_table('skills',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('proficiency is null or (proficiency between 0 and 100)', name=op.f('ck_skills_proficiency_range')),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], name=op.f('fk_skills_category_id_skill_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index('ix_skills_category_id', 'skills', ['category_id'], unique=False)
    op.create_table('about_content',
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('biography', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('portrait_media_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_about_content_single_row')),
    sa.ForeignKeyConstraint(['portrait_media_id'], ['media_assets.id'], name=op.f('fk_about_content_portrait_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about_content'))
    )
    op.create_table('achievements',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('achievement_type', sa.String(length=32), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('date_label', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_id', sa.String(length=128), nullable=True),
    sa.Column('verification_url', sa.String(length=512), nullable=True),
    sa.Column('document_media_id', sa.Uuid(), nullable=True),
    sa.Column('image_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("achievement_type in ('certificate','award','competition','presentation','milestone')", name=op.f('ck_achievements_achievement_type_valid')),
    sa.ForeignKeyConstraint(['document_media_id'], ['media_assets.id'], name=op.f('fk_achievements_document_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_media_id'], ['media_assets.id'], name=op.f('fk_achievements_image_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('slug', name=op.f('uq_achievements_slug'))
    )
    op.create_table('home_content',
    sa.Column('greeting', sa.String(length=128), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('technology_highlights', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('notes_label', sa.String(length=128), nullable=True),
    sa.Column('notes_lines', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('primary_cta_label', sa.String(length=64), nullable=True),
    sa.Column('primary_cta_href', sa.String(length=512), nullable=True),
    sa.Column('resume_media_id', sa.Uuid(), nullable=True),
    sa.Column('background_video_id', sa.Uuid(), nullable=True),
    sa.Column('background_poster_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_home_content_single_row')),
    sa.ForeignKeyConstraint(['background_poster_id'], ['media_assets.id'], name=op.f('fk_home_content_background_poster_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['background_video_id'], ['media_assets.id'], name=op.f('fk_home_content_background_video_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_media_id'], ['media_assets.id'], name=op.f('fk_home_content_resume_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_home_content'))
    )
    op.create_table('music_tracks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_media_id', sa.Uuid(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_media_id'], ['media_assets.id'], name=op.f('fk_music_tracks_audio_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_assets.id'], name=op.f('fk_music_tracks_cover_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music_tracks'))
    )
    op.create_table('projects',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_title', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deployment_note', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('solutions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('live_url', sa.String(length=512), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('live','local','in-progress','archived')", name=op.f('ck_projects_project_status_valid')),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_assets.id'], name=op.f('fk_projects_cover_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', name=op.f('uq_projects_slug'))
    )
    op.create_index('ix_projects_display_order', 'projects', ['display_order'], unique=False)
    op.create_table('site_settings',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('monogram', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('og_image_id', sa.Uuid(), nullable=True),
    sa.Column('favicon_id', sa.Uuid(), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_location', sa.String(length=255), nullable=True),
    sa.Column('footer_note', sa.Text(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_site_settings_single_row')),
    sa.ForeignKeyConstraint(['favicon_id'], ['media_assets.id'], name=op.f('fk_site_settings_favicon_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['og_image_id'], ['media_assets.id'], name=op.f('fk_site_settings_og_image_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    op.create_table('project_highlights',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_highlights_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_highlights'))
    )
    op.create_index('ix_project_highlights_project_id', 'project_highlights', ['project_id'], unique=False)
    op.create_table('project_media',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_project_media_media_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_media_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_media')),
    sa.UniqueConstraint('project_id', 'media_id', name='uq_project_media')
    )
    op.create_table('project_technologies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_technologies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_technologies')),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_technology')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_technologies')
    op.drop_table('project_media')
    op.drop_index('ix_project_highlights_project_id', table_name='project_highlights')
    op.drop_table('project_highlights')
    op.drop_table('site_settings')
    op.drop_index('ix_projects_display_order', table_name='projects')
    op.drop_table('projects')
    op.drop_table('music_tracks')
    op.drop_table('home_content')
    op.drop_table('achievements')
    op.drop_table('about_content')
    op.drop_index('ix_skills_category_id', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_publish_snapshots_created_at', table_name='publish_snapshots')
    op.drop_table('publish_snapshots')
    op.drop_index('ix_media_assets_kind', table_name='media_assets')
    op.drop_index('ix_media_assets_folder', table_name='media_assets')
    op.drop_index('ix_media_assets_checksum', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('social_links')
    op.drop_table('skill_categories')
    op.drop_table('music_settings')
    op.drop_table('expertise_items')
    op.drop_table('education_entries')
    op.drop_index('ix_contact_messages_is_read', table_name='contact_messages')
    op.drop_index('ix_contact_messages_created_at', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_table('career_entries')
    # ### end Alembic commands ###
